[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
TVMFFI = "b9edd577-36ff-4738-b9a8-ebb7fbd77e94"

[sources]
TVMFFI = {path = ".."}

[compat]
BenchmarkTools = "1"
julia = "1.10"
